name: XiShopConnector
version: '1.0.0'
main: com.xishop.connector.XiShopConnector
api-version: '1.20'
author: YourName
description: 'Connects Minecraft servers to the xishop web platform.'
website: https://xishop.com
commands:
  xishop:
    description: Main command for XiShopConnector.
    aliases: [xs]
    permission: xishop.admin
    usage: /<command> [reload|forcecheck|status]
permissions:
  xishop.admin:
    description: Grants access to all XiShopConnector commands.
    default: op
  xishop.reload:
    description: Allows reloading the plugin configuration.
    default: op
  xishop.forcecheck:
    description: Allows forcing a check for new commands.
    default: op
  xishop.status:
    description: Allows checking the plugin's connection status.
    default: op 